application: wikitheoria-hrd
version: 148
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api.*
  script: api.app

- url: /static
  static_dir: static

- url: /static/images
  static_dir: static/images
  
- url: /static/css
  static_dir: static/css
    
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /module/new.*
  script: modules.app
  login: required

- url: /module/edit.*
  script: modules.app
  login: required

- url: /modules.*
  script: modules.app

- url: /administration.*
  script: admin.app
  login: required

- url: /article/new.*
  script: articles.app
  login: required

- url: /article/edit.*
  script: articles.app
  login: required
  
- url: /articles.*
  script: articles.app
 
- url: /users.*
  script: users.app
  
- url: /contribute/definition.*
  script: terms.app
  login: required
  
- url: /contribute/term.*
  script: terms.app
  login: required
  
- url: /terms.*
  script: terms.app
  
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on